sudo: required
services:
  - docker

before_install:
  - docker build -t nalli/docker-protractor-cucumber-typescript .

  script:
  - docker run nalli/docker-protractor-cucumber-typescript npm run test -- --coverage